// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  articles: dynamic(() => import("./Articles")),
  career_history: dynamic(() => import("./CareerHistory")),
  contact_me: dynamic(() => import("./ContactMe")),
  hero: dynamic(() => import("./Hero")),
  integrations: dynamic(() => import("./Integrations")),
  links_list: dynamic(() => import("./LinksList")),
  rich_text: dynamic(() => import("./RichText")),
  showcase: dynamic(() => import("./Showcase")),
  skills: dynamic(() => import("./Skills")),
};
